name: Push to master

on:
  push:
    branches:
      - master

jobs:
  labels:
    name: Update repo labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Update labels
        uses: crazy-max/ghaction-github-labeler@v3.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  example:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Example
        shell: bash
        run: |
          echo -e "\n[INFO] Example from ${{ github.ref }}"
