name: Master branch

on:
  push:
    branches: master

jobs:
  example:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Example
        shell: bash
        run: |
          echo -e "\n[INFO] Example from ${{ github.ref }}"
