name: Other branches

on:
  push:
    branches-ignore: master

jobs:
  example:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Example
        shell: bash
        run: |
          echo -e "\n[INFO] Example from ${{ github.ref }}"

  pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create pull request - dependency (conditional)
        if: startsWith(github.ref, 'refs/heads/dependency')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: automatic,dependency
          template: .github/PULL_REQUEST_TEMPLATE/DEPENDENCY.md
          old_string: "<!-- Write you description here -->"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true

      - name: Create pull request - bugfix (conditional)
        if: startsWith(github.ref, 'refs/heads/bugfix')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: automatic,bugfix
          template: .github/PULL_REQUEST_TEMPLATE/BUGFIX.md
          old_string: "<!-- Write you description here -->"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true

      - name: Create pull request - feature (conditional)
        if: startsWith(github.ref, 'refs/heads/feature')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: automatic,feature
          template: .github/PULL_REQUEST_TEMPLATE/FEATURE.md
          old_string: "<!-- Write you description here -->"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true

      - name: Create pull request - documentation (conditional)
        if: startsWith(github.ref, 'refs/heads/documentation')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: automatic,documentation
          template: .github/PULL_REQUEST_TEMPLATE/DOCUMENTATION.md
          old_string: "<!-- Write you description here -->"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true

      - name: Create pull request - other (conditional)
        if: startsWith(github.ref, '!refs/heads/dependency') && startsWith(github.ref, '!refs/heads/bugfix') && startsWith(github.ref, '!refs/heads/feature') && startsWith(github.ref, '!refs/heads/documentation')
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: automatic,feature
          template: .github/PULL_REQUEST_TEMPLATE/FEATURE.md
          old_string: "<!-- Write you description here -->"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true
